export const RouterName = {
    login: "/",
    board: "/board",
    trakorps: "/trakorps",
    trakorpsDetail: "/trakorps-detail",
    trakorpsDetailSejarah: "/trakorps-detail-sejarah",
    trakorpsDetailLambangSatuan: "/trakorps-detail-lambang-satuan",
    trakorpsDetailTradisiSatuan: "/trakorps-detail-tradisi-satuan",
    trakorpsDetailDataPrestasi: "/trakorps-detail-data-prestasi",
    trakorpsDetailHymne: "/trakorps-detail-hymne",
    trakorpsDetailMars: "/trakorps-detail-mars",
    trakorpsDetailDataPejabatDansat: "/trakorps-detail-data-pejabat-dansat",
    trakorpsDetailDataPurnawirawan: "/trakorps-detail-data-purnawirawan",
    // Binman
    binman: "/binman",
    binmanPers: "/binman-personel",
    binmanPersList: "/binman-personel-list",
    binmanPetaJabatan: "/binman-peta-jabatan",
    binmanPetaJabatanList: "/binman-peta-jabatan-list",
    binmanKompersSatjar: "/binman-kompers-satjar",
    // Binmat
    binmat: "/binmat",
    binmatSub: "/binmat-sub",
    binmatSatuan: "/binmat-satuan",
    binmatList: "/binmat-list",
    // Binsiapsat
    binsiapsat: "/binsiapsat",
    binsiapsatSatuan: "/binsiapsat-satuan",
    binsiapsatSatuanPembinaan: "/binsiapsat-satuan-pembinaan",
    binsiapsatSatgasMenus: "/binsiapsat-satgas-menus",
    binsiapsatSatgasSatuan: "/binsiapsat-satgas-satuan",
    // Buku Pintar
    bukuPintar: "/buku-pintar",
    bukuPintarList: "/buku-pintar-list",
}